server:
  port: 9909

spring:
  datasource:
    username: root
    password: jae7758521
    url: jdbc:mysql://localhost:3306/my-mybatis?userUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*Mapper.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml